name: franka-golf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - stable-baselines3
      - sai-rl
      - torch
      - gymnasium
      - numpy
      - scipy
      - opencv-contrib-python
      - matplotlib
      - pillow
      - moviepy
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - pre-commit
      # - imitation
